#summary Scribbles, notes, those kinds of things.
#labels Phase-Deploy,Phase-Implementation

= NautilusSvn v0.12 branch =

== Dependencies ==

  * python-configobj
  * python-pyinotify
  * python-gtk2
  * python-glade

== Running ==
{{{
xhost +local: # This is required to be able to connect to the X Server after sudoing

sudo adduser nautilussvn
sudo -i -u nautilussvn

svn checkout http://nautilussvn.googlecode.com/svn/branches/v0.12/ ~/nautilussvn

mkdir -p ~/.nautilus/python-extensions
ln -s ~/nautilussvn/nautilussvn/lib/extensions/nautilus/__init__.py ~/.nautilus/python-extensions/NautilusSvn.py
mkdir -p ~/.icons
ln -s ~/nautilussvn/nautilussvn/data/icons/hicolor ~/.icons/ 

export PYTHONPATH="$PYTHONPATH:/home/$USER/nautilussvn/"
mkdir -p /tmp/nautilussvn_nautilus-testing
export TMPDIR=/tmp/nautilussvn_nautilus-testing
nautilus --no-desktop .
}}}


= No never ending loop? =
In a [http://code.google.com/p/nautilussvn/source/browse/branches/v0.12/nautilussvn/lib/extensions/nautilus/NautilusSvn.py?spec=svn362&r=362#218 particular revision] there was a function update_emblem which was called by update_file_info but which indirectly called update_file_info back by calling NautilusVFSFile.invalidate_extension_info. Everything logical told me this should cause a neverending loop, but that wasn't the case. I never found out why that did not happen. 